# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself


default_platform(:ios)

platform :ios do
  desc "Build App to testflight"
  lane :beta do
  #setup_travis
  #xcversion(version: "10.2

  # Fetch the keychain env variables
      # securely stored in the travis.yml.
      keychain_name = ENV["MATCH_KEYCHAIN_NAME"]
      keychain_password = ENV["MATCH_KEYCHAIN_PASSWORD"]


  # Create a temporary keychain to
     # store the certificates.
     create_keychain(
       name: keychain_name,
       password: keychain_password,
       default_keychain: true,
       unlock: true,
       timeout: 3600,
       add_to_search_list: true
     )

     # Fetch the necessary certificates and
        # provisioning profiles.
        match(
          keychain_name: keychain_name,
          keychain_password: keychain_password,
          readonly: true
        )

        # Increment the build number using the
          # latest Testflight build number.
          increment_build_number(
            build_number: latest_testflight_build_number() + 1
          )

      # Build the application using the
      # specified scheme.
      build_app(scheme: "teachMe")

      # Upload the application to Testflight
      upload_to_testflight

      # Remove the temporary keychain leaving
    # no trace.
    delete_keychain(
      name: keychain_name
    )

#  match(type: "appstore", readonly: true)
#  sync_code_signing
#  disable_automatic_code_signing(path: "teachMe.xcworkspace")
#  build_app
#  enable_automatic_code_signing(path: "my_project.xcodeproj")
  #upload_to_testflight
  # Build and deploy to TestFlight
  #build_app(export_method: "app-store")
  # build_app(export_xcargs: "-allowProvisioningUpdates")
#  upload_to_testflight
  end
end
