# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself


default_platform(:ios)

platform :ios do
  desc "Build App to testflight"
  lane :beta do
  #setup_travis
  #xcversion(version: "10.2

  # Fetch the keychain env variables
      # securely stored in the travis.yml.
      keychain_name = ENV["MATCH_KEYCHAIN_NAME"]
      keychain_password = ENV["MATCH_KEYCHAIN_PASSWORD"]


  # Create a temporary keychain to
     # store the certificates.
     create_keychain(
       name: keychain_name,
       password: keychain_password,
       default_keychain: true,
       unlock: true,
       timeout: 3600,
       add_to_search_list: true
     )

     # Fetch the necessary certificates and
        # provisioning profiles.
        match(
          keychain_name: keychain_name,
          keychain_password: keychain_password,
          readonly: true,
          type: "appstore"
        )

        # Increment the build number using the
          # latest Testflight build number.
          #latest_testflight_build_number()
          increment_build_number(
            build_number:  latest_testflight_build_number() + 1
          )

         # disable_automatic_code_signing(code_sign_identity: 'iPhone Distribution')
         # sync_code_signing(type: "appstore")
         # update_project_provisioning(profile: ENV['sigh_petitcoding.com.teachMe_appstore_profile-path'])

      # Build the application using the
      # specified scheme.
      build_app(scheme: "teachMe", export_method: "app-store")

      # Upload the application to Testflight
      #upload_to_testflight(
       # skip_waiting_for_build_processing: true
      #)
      pilot upload --skip_submission

    # Remove the temporary keychain leaving
    # no trace.
    delete_keychain(
      name: keychain_name
    )

  end
end
