# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["MATCH_KEYCHAIN_NAME"] = "KeychainNameFastFile"
ENV["MATCH_KEYCHAIN_PASSWORD"] = "fastfiledev"

default_platform(:ios)
  

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do   
    increment_build_number
    disable_automatic_code_signing(path: "teachMe.xcworkspace")
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
    get_certificates           
    get_provisioning_profile
    enable_automatic_code_signing(path: "teachMe.xcworkspace")
    build_app(scheme: "teachMe")
    upload_to_testflight
  end
end
